from app.models import (
    Course,
    DiagnosticAnswer,
    DiagnosticQuestion,
    DiagnosticTest,
    Exercise,
    Lesson,
    Module,
    ModuleProgress,
    Progress,
    SkillMapping,
    Submission,
    TestCase,
    TheoryBlock,
    Topic,
    User,
    UserSkill,
)

__all__ = [
    "Course",
    "DiagnosticTest",
    "DiagnosticQuestion",
    "DiagnosticAnswer",
    "SkillMapping",
    "Module",
    "ModuleProgress",
    "Lesson",
    "Topic",
    "TheoryBlock",
    "Exercise",
    "TestCase",
    "Progress",
    "User",
    "Submission",
    "UserSkill",
]
